### ISSUE TITLE
Warning message in commented area

### ISSUE THREAD

**Issue by NoOorZ24** [jsfiddle/jsfiddle-issues#1012]
Just a little buggy thing i noticed is that if I have HTML code containing script tags commented between /* */ in JS section then page displays warning: **Input plain JavaScript code, no HTML.**  It's a bit annoying. And another thing with this is that the warning message hides last line of my code when scrolled to the bottom

**Comment by oskarkrawczyk** [comment]
Unfortunately the codebase for the current JSFiddle version is frozen and no minor issues will be addressed. 

We're all hands on the rewrite and in order to get it out sooner rather than later, we can't spend time on addressing this in the legacy codebase.

The new rewritten codebase will not have this issue.
