### ISSUE TITLE
[UI/UX] Warning messages blocks user from editing the warning away

### ISSUE THREAD

**Issue by benri** [jsfiddle/jsfiddle-issues#1018]
warning / error messages are blocking the user from making changes that would hide such messages

![screen shot 2017-05-17 at 11 52 11 am](https://cloud.githubusercontent.com/assets/6927404/26170744/576027e2-3af7-11e7-9026-113ab70dc502.png)

suggested possible solutions:
* messages with x to close messages
* messages isn't displayed over the code box, but appended beneath it

**Comment by oskarkrawczyk** [comment]
Unfortunately the codebase for the current JSFiddle version is frozen and no minor issues will be addressed. 

We're all hands on the rewrite and in order to get it out sooner rather than later, we can't spend time on addressing this in the legacy codebase.

The new rewritten codebase will not have this issue.
