### ISSUE TITLE
Show web pages around the web that links to opened fiddle

### ISSUE THREAD

**Issue by ismusidhu** [jsfiddle/jsfiddle-issues#1023]
It would be good to refer to what people talk about this fiddle around the web. Most importantly on stackoverflow.com

**Comment by oskarkrawczyk** [comment]
Unfortunately the codebase for the current JSFiddle version is frozen and no new features will be added. 

We're all hands on the rewrite and in order to get it out sooner rather than later, we can't spend time on getting new features into the legacy codebase.

You can have a look at the potential and approved features on our roadmap: https://trello.com/b/LakLkQBW/jsfiddle-roadmap
