### ISSUE TITLE
Buttons that overlap the code.

### ISSUE THREAD

**Issue by damiantoczek** [jsfiddle/jsfiddle-issues#1030]
Hello,
i want to post here a fast issue, i don't know how all this here works, usualy websites use forums or Twitter.

There are 4 buttons that overlap the view and i don't know why these buttons NEED to be in the "Editor Windows" where i write the code and not in the navigation bar.

http://i.imgur.com/60aDSed.png

**Comment by oskarkrawczyk** [comment]
Unfortunately the codebase for the current JSFiddle version is frozen and no minor issues will be addressed. 

We're all hands on the rewrite and in order to get it out sooner rather than later, we can't spend time on addressing this in the legacy codebase.

The new rewritten codebase will not have this issue.
