### ISSUE TITLE
Bug: Three.js resizing via document.body scales incorrectly

### ISSUE THREAD

**Issue by backspaces** [jsfiddle/jsfiddle-issues#1039]
Here is a simple Three.js program: http://backspaces.net/temp/pointsbody.html
The useBody toggles between window innerWidth/Height and document.body clientWidth/Height.
Toggling and resizing works basically the same between the two.

Here is the exact duplicate fiddle: https://jsfiddle.net/backspaces/xppL8vok/
When you start it you will see nothing or a tiny version of the scene. 

Using the console you will see a getSize log, with a small or zero height .. definitely not the document.body's. Type document.body.clientHeight into the console to double check.

Resize in/out a couple of times and the scene grows.

Reload the page .. back to tiny. Now click on useBody to toggle it off. Now you see the expected scene. Toggle it back off and you get incorrect scaling while resizing.

So the issue is that the backspaces.net version scales correctly in either mode but the fiddle only scales correctly with useBody off, i.e. in window measurements.

**Comment by oskarkrawczyk** [comment]
Might be that embedding it inside of an `iframe` breaks things in Three.js - not sure, I don't know that library well enough. 

The iframe in JSFiddle itself is very basic, no magic there, so to be the script needs to be readjusted to work in this environment rather than something having to be fixed in JSFiddle.
