### ISSUE TITLE
Mention about default's load type: onload somewhere else than only in Javascript drop-down menu.

### ISSUE THREAD

**Issue by maszynka** [jsfiddle/jsfiddle-issues#1055]
I was creating reduced test case for my problem and I found out that jsfiddle doesn't run my knockout's code properly while stacks fiddle does:

[https://jsfiddle.net/maszynka/uc25p6j9/1/](https://jsfiddle.net/maszynka/uc25p6j9/1/)

StackOverflow:
![knockout edit observablearray elements observable property stack overflow](https://user-images.githubusercontent.com/2837542/29408443-8081e284-8348-11e7-9497-c02ca8d0e6db.png)

It took me a while to understand that the default wrapper for js is onload event (which might crash code).

**Comment by oskarkrawczyk** [comment]
Unfortunately the codebase for the current JSFiddle version is frozen and no new features will be added. 

We're all hands on the rewrite and in order to get it out sooner rather than later, we can't spend time on getting new features into the legacy codebase.

Since the new JSFiddle will have a reworked UI, there will be most likely a place to display the load type.
