### ISSUE TITLE
Cannot reset layout in new version of JSFiddle.

### ISSUE THREAD

**Issue by ryanpcmcquen** [jsfiddle/jsfiddle-issues#1151]
This no longer works: `Layout.setWindowSizes(null)`

**Comment by oskarkrawczyk** [comment]
Layout was rewritten, no need for resetting this way.

**Comment by ryanpcmcquen** [comment]
Is there any way to restore the initial size? I still like being able to do that, even if there is 'no need'.

**Comment by oskarkrawczyk** [comment]
You can remove panel size settings in your Local Storage (keys are called `grid_*-split-sizes`).

**Comment by ryanpcmcquen** [comment]
Thank you!

**Comment by monkeytroy** [comment]
I think this needs to be reopened.  After installing a 2nd monitor my fiddle pages jumped and the right panels disappeared.  Neither of these two fixes seem to work for me.   Cleared local storage for jsfiddle and the right panels are still missing.. well they are pushed far off the screen to the right.  Cleared cache too.  No change.  

Investigating the dom, my div with id="content" has a width of 15000.   
It's parent, layout-container, has 
![2019-07-25 16_22_09-Canvas Circle Test 2 - JSFiddle](https://user-images.githubusercontent.com/39935/61906048-8059c500-aef8-11e9-9310-0aa132af8560.png)
![2019-07-25 16_22_41-](https://user-images.githubusercontent.com/39935/61906049-8059c500-aef8-11e9-8285-29dcf5f2a194.png)

a normal width of 1920.   

Trying to set this with a style width="10%" works temporarily and the right panel is visible.  But page refresh it goes back to what it was.

I was able to fix it, also temporarily, by reloading page.  Adjusting the horizontal divider. Editing the matrix of panel sizes that now show up in the local storge.  

After reload the value is: [[50,50],[53,47],[50,50]]
Seems to be pct values for split.  [ [Left,Right], [LeftTop, LeftBottom], [RightTop, RightBottom]]
The 50/50 value for the left right split should be correct.. if my #content panel was not 15000px.   Which persists across loads.  

I changed it to:  [[5,95],[50,50],[50,50]]
And now the panel is visible... but its still broken.  Since..  5% width is not right.

**Comment by monkeytroy** [comment]
I just noticed that this messes up my other fiddles.  Its only the two fiddles that were open when I added the 2nd monitor that are FUBAR.  But it shows me that the content width is somehow saved server side on a per fiddle basis.. that was seems to be anyway.

**Comment by sheriffderek** [comment]
How about a button that clears this?
