### ISSUE TITLE
Broken Editor!

### ISSUE THREAD

**Issue by Brian151** [jsfiddle/jsfiddle-issues#1153]
Same problem as #1136 

Only, it is happening on the Pale Moon Web Browser

Can't access a tool I wrote for processing web console logs, now, so I gotta store a bunch of extra text in my url list that I don't need/want...

I do hope this can be fixed in a reasonable amount of time?

**Comment by oskarkrawczyk** [comment]
Same problem, meaning it doesn't work on mobile?

Tested on mobile Chrome and Safari, works fine.

If you're having issues with the desktop version, first please refresh all cache, and try again. If the issue persists, please provide a screenshot, any errors that appear in the devtools console.

Closing for now since as far as I can see JSFiddle works fine on any browsers available to me (didn't test on `Pale Moon Web Browser`).
