### ISSUE TITLE
single quotes are also must be allowed not only double quotes

### ISSUE THREAD

**Issue by hunboy** [jsfiddle/jsfiddle-issues#1158]
Now jsfiddle throws a warning when I use &lt;div id='something'&gt;&lt;/div&gt; because of single quote, although by the spec single quote is legal for XML and HTML

**Comment by epistemex** [comment]
I wanted to add since it's related: there is no requirement for quotes at all (except from in XHTML) unless the attribute value contains ASCII whitespace (such as regular space) or special chars.  From https://html.spec.whatwg.org/multipage/introduction.html#intro-early-example:

> Attributes are placed inside the start tag, and consist of a name and a value, separated by an "=" character. The attribute value can remain unquoted if it doesn't contain ASCII whitespace or any of " ' ` = &lt; or &gt;. Otherwise, it has to be quoted using either single or double quotes. The value, along with the "=" character, can be omitted altogether if the value is the empty string.

For example, this is valid:

    <canvas width=500 ...>

But jsfiddle complains double quotes are needed.

**Comment by oskarkrawczyk** [comment]
Removed that linting rule.
