### ISSUE TITLE
Don't trigger auto-run when inside a comment

### ISSUE THREAD

**Issue by realsrikar** [jsfiddle/jsfiddle-issues#1171]
Editing comments doesn't affect the code so it doesn't make sense to re-run it.

**Comment by oskarkrawczyk** [comment]
I had a quick look into it, seems like a lot of work for very little benefit. 

I'll leave this ticket open for a period of time, maybe other people will request this as well.

**Comment by realsrikar** [comment]
Single line comments `//` would be easier to imlement than block level comments `/* */` because they end at the end of the line.

**Comment by oskarkrawczyk** [comment]
Both are pretty much the same difficulty since the code tree would have to be parsed, and detected when the cursor is inside of a `code.comment` context (for each language that JSFiddle provides).

If someone could do a mockup implementation using the latest CodeMirror, would be easier to integrate it in the editor.

**Comment by oskarkrawczyk** [comment]
Note to self: `editor.getTokenTypeAt(editor.doc.getCursor())` does the job of fetching the code tree context, when in comment it'll return the `comment` token.
