### ISSUE TITLE
Cannot Save fiddle

### ISSUE THREAD

**Issue by mrmarkichs** [jsfiddle/jsfiddle-issues#1173]
Some of my students cannot save any fiddle. After clicking on the Save button nothing happens. When they try to exit they get a message about an unsaved fiddle.

All the students are using MacBook Pro laptops, but only some students are having a problem. I think they are on Sierra. 

I tried suggesting using Chrome or Firefox instead of Safari, but that doesn't help. I've used jsfiddle with my class for three years now. This is a brand new issue.

Suggestions?

Thank you.
Mark

**Comment by oskarkrawczyk** [comment]
The only thing I can suggest is refreshing browser cache since any old versions might cause odd behavior.

As far as I see all works as expected, saving, updating, forking, etc.

If refreshing cache doesn't help, please check if there are any JS errors in the console – providing these will definitely help pinpointing any potential problems.

**Comment by mrmarkichs** [comment]
Wow! Thanks for the super quick response. Will definitely check the cache issue out first thing when school opens again a week from Monday.

If needed, how can I check JS errors in the console?

**Comment by oskarkrawczyk** [comment]
https://developers.google.com/web/tools/chrome-devtools/console/

--

**Comment by oskarkrawczyk** [comment]
Had no other reports about problems with saving. Closing.

**Comment by lhale** [comment]
I'm logged in to JSFiddle , but there's no Save button for my new fiddle. There's Update, Form, but no Save where I can rename it. What's going on ?

**Comment by oskarkrawczyk** [comment]
@lhale Create a new issue with a screenshot, the example fiddle, browser you're using, and any other details that might help understanding your problem.

**Comment by edwardtilley** [comment]
Am having this problem as well... refreshed all Ctrl-F5 - doesn't make a difference - Using Chrome on Windows 8.1 btw

**Comment by pikl-cz** [comment]
I have the same problem - I am logged in. This problem lasts longer period (months minimally). I know it because I tried to save same of my snippets about 1 year ago. It discouraged me to use jsfiddle and today I wanted to give a new chance but the same problem. I can write fiddle, run it - it works. I save it and when I open it from list in my fiddles I see just some version which is missing many lines of code.

**Comment by oskarkrawczyk** [comment]
You didn't save the fiddle as the base version which is why you see order version in your listing.

It's been always like that.

**Comment by pikl-cz** [comment]
@oskarkrawczyk  thanks. that is it. 

from UX point of view I would mark more that it is necessary set base version - it was really confusing (I was also losing title and description). it is not too intuitive.

**Comment by oskarkrawczyk** [comment]
There's a link to the latest version of the fiddle in the listing. Title and description are a part of the version.
