### ISSUE TITLE
Incorrect error: "Missing () when invoking constructor"

### ISSUE THREAD

**Issue by epistemex** [jsfiddle/jsfiddle-issues#1232]
The code validator incorrectly states that parenthesis is missing when invoking a constructor using `new`:

![2018-04-06_10-22-57](https://user-images.githubusercontent.com/26116778/38430075-d60ad4c4-3985-11e8-8662-b003de88dc76.jpg)

However, a argument list is optional and doesn't have to be provided if there are no arguments to the constructor function used with `new`:

    let img = new Image;            // is correct

other cases:

    let d = (new Date).toString();  // is correct

however:

    let d = new Date.toString();    // is incorrect due to precedence order

Of course, people use parenthesis for consistency, linters may protest (also due to consistency) etc. but it's not technically an error and shouldn't be marked/highlighted as such.

Spec reference: http://es5.github.io/x11.html#x11.2.2(5): (incl. ES3-6)

> Return the result of calling the [[Construct]] internal method on constructor, providing no arguments (that is, an empty list of arguments)

[Result case](https://jsfiddle.net/epistemex/05zgouvb/)

**Comment by oskarkrawczyk** [comment]
Thanks, but these are so minor things that it's better for you to turn off the linter if it bothers you.

JSHint is opinionated and these opinions have merits - as you stated "consistency".

Closing, since I'm 99% sure JSHint folks won't be bothered to address this, as they don't address major linter problems.
