### ISSUE TITLE
Fiddle not loading on IE 11

### ISSUE THREAD

**Issue by ThomasFerro** [jsfiddle/jsfiddle-issues#1257]
Hi !

It seems that every Fiddles couldn't load in IE (11) due to an error with the `_dist-editor.js` file.

I've got a `SCRIPT438:Object doesn't support property or method 'forEach'` error every time I try to open a project with this browser only.

Here's a screenshot of the console (in french, sorry for that) :

![Console](https://user-images.githubusercontent.com/14331186/39180707-e4e8487e-47b7-11e8-8722-2efcf7194ed1.png)

**Comment by oskarkrawczyk** [comment]
Yes, we officially don't support IE. I might fix that issue when I have the time.

**Comment by ThomasFerro** [comment]
Oh, ok, didn't know that IE wasn't supported at all.

Thanks for your time !

**Comment by oskarkrawczyk** [comment]
Yeah, IE users on JSFiddle is less than 2%, so no point putting effort in maintaining oldschool code just to have it working on IE.

**Comment by ThomasFerro** [comment]
Totally agree, it's just that I'm working on POCs that are supposed to be integrated in a product for every browser. 
I was used to develop on Firefox with JsFiddle and then just run the Fiddle on every other browser.

**Comment by JabbyPanda** [comment]
>IE users on JSFiddle is less than 2%

That's true, but we would like to use JSFiddle to showcase Javascript issues related to IE only to our managers :)

**Comment by oskarkrawczyk** [comment]
@JabbyPanda to show a fiddle just add `/show/` to the end of the URL

**Comment by limonte** [comment]
1. IE11 is still **widely used** by a lot of public authorities because of security restrictions.
2. IE11 is used by **23.3%** of disabled people according to the latest survey https://webaim.org/projects/screenreadersurvey7/ 
3. We are using jsfiddle templates for modern and old (IE11, Android) browsers: https://github.com/sweetalert2/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md

It might be worth to reconsider IE11 support. JSBin has the perfect IE11 support.

**Comment by oskarkrawczyk** [comment]
Closing this ticket. JSFiddle will not support IE, for reasons stated above.

**Comment by phillip-haydon** [comment]
JSBin works flawlessly @limonte, thanks for the heads up.
