### ISSUE TITLE
Inaccessibility of service in Russia

### ISSUE THREAD

**Issue by nektobit** [jsfiddle/jsfiddle-issues#1260]
Hello, maybe I'm publishing this question in the wrong place. In this case, please indicate the url at the address of which I can publish my question and close this issue.
Since April 16, 2018, the Russian Internet registrar RosKomNadzor has blocked jsfiddle.net on the territory of Russia. I managed to find out that they blocked the ip address for "terrorist activities". But they did not block the domain jsfiddle.net.
In response to my appeal, I received a message stating that other sites that are prohibited in Russia can be located at this ip address.
I want to challenge this decision.
Tell me, can I somehow make sure that ip address 165.227.250.163 is used only for jsfiddle.net?
I tried the service http://reverseip.domaintools.com/search/?q=165.227.250.163
It issues only one domain name.
Can I somehow make sure of this?

**Comment by oskarkrawczyk** [comment]
Hi @nektobit 

It would seem we've been blocked around the time Telegram was banned and RosKomNadzor cut out millions of IP's (including Google and Amazons).

I assumed that there's nothing that can be done because it's a political decision, and having them say that our IP was blocked because of `terrorist activities` is pretty much saying that they won't be unblocking it anytime soon - because you know... terrorists, fear them, they're doing it for your good...

Now that said, and putting my inner-sceptic aside.

`165.227.250.163` is being used only by JSFiddle, it's assigned to us by Digital Ocean. Maybe what they meant was that a pool of addresses including the aforementioned `are prohibited in Russia`, which would make sense because the pool is quite large and who knows what's there (Telegram?).

Can you tell me how do you get in touch with them, is there a way to talk in English with their support? Maybe I'll try to reach out personally.

**Comment by nektobit** [comment]
Hi @oskarkrawczyk 

You are absolutely right, jsfiddle was blocked at the same time as the confrontation between Russia and telegrams began, I checked it.
I communicate with them through a form on the official website of the Roskomadzor. It takes several days, because Russia is a country of bureaucrats. However, they are obliged to respond to my request, because this is a public institution. I will send one more appeal and ask for contacts to conduct a dialogue in English for you.
Then two scenarios are possible:
1. They will go to a dialogue
2. They will give an official (useless) answer and will not do anything. In this case, I will try to attract as much attention to this precedent, attract media.

**Comment by nektobit** [comment]
@oskarkrawczyk
Yes, it helped. The site began to appear normally after a few minutes after changing ip. Some providers have not yet updated ns, but it's only a matter of time. It is a pity that the issue was resolved in this way, programmers should not suffer because of government actions. However, your decision closes the problem as quickly as possible: o)
Thank you.
