### ISSUE TITLE
Save is super confusing

### ISSUE THREAD

**Issue by greggman** [jsfiddle/jsfiddle-issues#1345]
Not sure where to post this but I find the new save vs update workflow super super confusing.

AFAIK I never want to pick save. I only every want to pick Update and/or Fork. Save seems to be effectively "SaveAs". It saves a new copy. It does effectively the same thing as "Fork" AFAICT.

So what happens. 

* I open an old fiddle.
* There is no "Save option" (good!)
* I pick "Fork"
* work on stuff
* I pick "Save" (because seeing the word Save fits 40 years of using computers)

What happens

I now have 2 fiddles. The one created when I picked "fork" and the one created when I picked "Save". I didn't want this second fiddle.

What should happen?

There should be no save button.

What is the point of the Save button? I don't understand what it's for. It wasn't there a month or 2 ago.

I hope this is useful feedback.

**Comment by oskarkrawczyk** [comment]
We have this working like that since day one of JSFiddle, this is the first time in memory anyone mentioned that saving is confusing :)

- `Save` - only available on NEW fiddles, saves the current code into a fiddle
- `Update` - available on EXISTING fiddles, updates current fiddle by adding a version
- `Fork` - forks ANY fiddle into a new fiddle

As far as I can see all works as expected.

**Comment by greggman** [comment]
Something change recently then. `Save` is appearing in places it didn't appear before.

If I was to guess the new place it appears is after choosing `Fork`. It did **NOT** used to appear there. So now, if you pick `Fork` and then `Save` you've actually forked twice.

**Comment by oskarkrawczyk** [comment]
@greggman Hah, ok, something's not right. Will have a look into that, thanks!
