### ISSUE TITLE
The hello bar is just annoying

### ISSUE THREAD

**Issue by slikts** [jsfiddle/jsfiddle-issues#1372]
It doesn't even close if you select "Empty". I know several people who use a userscript to hide it. It shouldn't be shown by default.

**Comment by oskarkrawczyk** [comment]
Noted

**Comment by KyleMit** [comment]
It's not that the functionality is annoying in and of itself, it just feels like an intro tutorial / coach mark / release notes that I'm forced to navigate through every time I land on the page, even if I've opened jsFiddle 100 times already.

If you look at User Stories or User Task Flows or any telemetry you have, I'd reason that 90%+ of users never interact with the bar except being forced to close it before doing work.  When I type *jsfiddle.net* into my browser, my use case is pretty much 100% of the time is to start writing code, and having a large dialog that I have to dismiss adds friction to that experience.  It's like trying to open a messenger app to respond to a friend and it asks me to if I'd like to update.

If you used localstorage or something to display once per browser instance, that would be amazing.  Since it's toggle-able by clicking the logo anyway, users can get back to it anytime they want *if they want*.

**Comment by KyleMit** [comment]
Aha, I was debugging around to see if I could fix it with a user script, and noticed there's already a setting for it:

![image](https://user-images.githubusercontent.com/4307307/48780394-ceeafb80-eca7-11e8-9fdc-3b0c4a49de28.png)

It actually took me a minute to find this in the settings, even on the suspicion it already existed because I don't think of that exclusively as the "Boilerplate Bar" (maybe update copy?)

![image](https://user-images.githubusercontent.com/4307307/48780153-394f6c00-eca7-11e8-8eec-f7a971290ff5.png)

But thanks so much! Glad to see this is natively skippable.

**Comment by jwhitleybb** [comment]
@oskarkrawczyk I said "never", not less often ;) but I user JS chrome extension did the trick with $('#hello-bar').hide();

**Comment by jwhitleybb** [comment]
@KyleMit it seems like "less often" is still 50% of the time. 

I don't understand why this is being forced on users. It's bad UX.

**Comment by oskarkrawczyk** [comment]
Boilerplate bar will stay, and show by default.
