### ISSUE TITLE
Twitter blocks links from jsfiddle.net

### ISSUE THREAD

**Issue by zalun** [jsfiddle/jsfiddle-issues#1417]
Twitter is rejecting posts with JSFiddle URL inside.
If a URL shortener is used the unsafe page warning is displayed[1]
What is causing that?[2]

[1]
<img width="500" alt="screenshot 2019-01-25 07 20 22" src="https://user-images.githubusercontent.com/97885/51728798-ba452e00-2071-11e9-9be0-7ac8875fb604.png">
[2] We've tried to contact Twitter, but no answer.

**Comment by oskarkrawczyk** [comment]
At some point in the past crypto scammers used JSFiddle to host pages with a wallet code and posted links to that on Twitter.

Due to the nature of JSFiddle, anyone can post anything, so wallet codes are ok – we did implemented a content filter so shadow-ban these.

I asked Twitter if they they could help out and ban twitter accounts that were posting scam tweets that included links to the rouge fiddles.

Twitter just went the easy route and **blocked all jsfiddle.net links** instead of blocking spammer accounts on their platform.

Tried to contact Twitter many many times, with no reply whatsoever. They most likely have no-explanation-needed-policy, which is why they never replied.

There's nothing that can be done here unless somebody has contact to a higher op at Twitter who has the decision power to help out here.

**Comment by tomglynch** [comment]
By wallet code you mean a crypto mining script yes?

**Comment by applefreak** [comment]
> By wallet code you mean a crypto mining script yes?

I think I saw some variant of this. It's one of those "send some ETH and receive 2x more back!" With fake "live" transaction listing and fake testimonials.

**Comment by oskarkrawczyk** [comment]
@tomglynch No, I mean a wallet code, pretty much as @applefreak explained.

**Comment by jetrois** [comment]
pretty good reason to ditch twitter for mastodon. I dont get why its so hard for platforms to work with devs to fix issues.

**Comment by thecodeboy** [comment]
I had to shut down my URL shortening platform (5ly.me) after Twitter blacklisted it's URLs. Used to get 1M hits/month at it's peak. Now it's dust.

**Comment by dsignr** [comment]
> I had to shut down my URL shortening platform (5ly.me) after Twitter blacklisted it's URLs. Used to get 1M hits/month at it's peak. Now it's dust.

No offence but most URL shortening platforms add no value whatsoever other than forcing the user to watch some spammy ads, mine their data in the process and sell to other advertisers. Playing the devil's advocate, the other reason is, even if the service was legit, probably a high percentage of it was used by your users to spam/scam other people.

**Comment by Duologic** [comment]
This is starting to become a complain thread, please keep it on topic.

**Comment by jahrichie** [comment]
I preface what i'm about to say with Twitter sux...but why should twitter help your organization find a problem originating in your systems? Seems like YOU guys tried to take the easy way out, not them. 

Find a better way to validate the issue, plug the hole, and reach out to twitter. If they don't unblock your sharing urls, change them to a new url and reverse proxy the other url or something -- don't blame a social network for making a PERFECTLY ethical decision.

**Comment by anko** [comment]
@jahrichie 

> validate the issue, plug the hole, and reach out to twitter

They did those things.

Quoting @oskarkrawczyk's [above post](https://github.com/jsfiddle/jsfiddle-issues/issues/1417#issuecomment-457485228):

>  we did implemented a content filter to shadow-ban these

> Tried to contact Twitter many many times, with no reply whatsoever

What more do you think should be done?

**Comment by rafaelcavalcante** [comment]
"send some ETH and receive 2x more back!"

I shouldn't, but i'm very surprised

**Comment by oskarkrawczyk** [comment]
@zalun managed to get in touch with someone from Twitter and get us unblocked 🎉
