### ISSUE TITLE
Untitled fiddles showing as public

### ISSUE THREAD

**Issue by ThomasOrlita** [jsfiddle/jsfiddle-issues#1519]
1. Create a new empty fiddle
2. Add some content, don't add title or description
3. Click save
4. Go to My Fiddles -> Public
5. This fiddle is added there. It is also showing in the Untitled category

I thought by not giving a title to the fiddle, it'd stay private (link only), but it's appearing as a Public fiddle. What am I doing wrong or how to save it without making it public?

Also titled fiddles are shown under "Untitled":
![image](https://user-images.githubusercontent.com/17808846/72219806-55b50480-354a-11ea-967b-7aa13d18735c.png)

titled fiddle: https://jsfiddle.net/ThomasOrlita/Lwsjhkbr/
untitled fiddle: https://jsfiddle.net/ThomasOrlita/yesu6dox/

**Comment by oskarkrawczyk** [comment]
Untitled fiddles were never really "private", they were simply unlisted on the users public profile.

In the newest update both types of fiddles are listed on the public profile. An upcoming version will introduce true "private fiddles" that are hidden from any public listings as well as inaccessible by direct link.

> Also titled fiddles are shown under "Untitled"

I see where the issue lays, will fix.

**Comment by oskarkrawczyk** [comment]
Fixed.

**Comment by ApoloSiskos** [comment]
@oskarkrawczyk I am trying to save a private fiddle but it goes directly to the Public folder.

**Comment by ThomasOrlita** [comment]
Yeah, I have the same problem. All of my unlisted fiddles were shown on my public profile and new private fiddles are shown as public as well...

**Comment by oskarkrawczyk** [comment]
I'll reiterate again:

There's no such thing as a "private fiddle", we had **untitled fiddles** that were **unlisted** just because of the missing title, nothing more – they were **not private**, anyone with the link could access them, web scrapers could crawl them.

The way we reworked categorizing listings means both titled and untitled fiddles are listed on user's profile.

True private fiddles (ones that are unlisted, and completely unavailable to access by any other user, even with a direct link), will be available in the upcoming weeks.
