### ISSUE TITLE
Opening `*/show` does redirect back to edit mode

### ISSUE THREAD

**Issue by pawelfus** [jsfiddle/jsfiddle-issues#1578]
For example: https://jsfiddle.net/BlackLabel/gdsc4kvo/show redirects immediately to https://jsfiddle.net/BlackLabel/gdsc4kvo/

**Comment by oskarkrawczyk** [comment]
Indeed it does. This is due to the amount of scam scammers put on JSFiddle and link in full-screen mode.

Some people can't be cool, which is why we can't have nice things.

**Note that this was absolutely NEVER an official feature**, because in reality it was just a minor bug that wasn't causing too much harm so up until yesterday we just kept it in.

I am sorry if this was something you used to use a lot, but reality is reality, and this had to be fixed.

**Comment by oskarkrawczyk** [comment]
So I'm thinking about a potential solution.

@pawelfus Would the ability to link in full-screen, but requiring hitting a button to run that fiddle, be ok for your use-case?

If I bring this bug back, I'd need to make it a feature and require a users-action so scammers can't just render anything.

**Comment by pawelfus** [comment]
Ugh, sorry to hear that! Are you sure it wasn't intended feature? I think there used to be the "Show" button, maybe that was years ago.. 

> I am sorry if this was something you used to use a lot, but reality is reality, and this had to be fixed.

Don't worry, I didn't used that a lot. It's just a cool feature that I could create a demo and share it with other departments (sales, social etc). They don't really care about code inside :)

There's only one use-case that I will be missing - testing on mobile. With 2-3 panels, testing any demo in mobile is cumbersome. Adding just `/show` in URL was super easy and convenient.

> Would the ability to link in full-screen, but requiring hitting a button to run that fiddle, be ok for your use-case?

For me, even new layout with all hidden panles (only "result" displayed) would be fine. For example `https://jsfiddle.net/BlackLabel/gdsc4kvo#show` could open fiddle in desired layout?

**Comment by oskarkrawczyk** [comment]
> Are you sure it wasn't intended feature? 

Pretty sure. The view it is rendering is the embed view, this was never supposed to be rendered outside of the embed iframe.

> I think there used to be the "Show" button, maybe that was years ago.

Getting older, but I think I'd remember that 😉

> It's just a cool feature that I could create a demo and share it with other departments (sales, social etc). They don't really care about code inside :)

Yeah, this is something I haven't considered, and it is a valid case why there's should be a feature to present the result alone.

> There's only one use-case that I will be missing - testing on mobile. With 2-3 panels, testing any demo in mobile is cumbersome. Adding just /show in URL was super easy and convenient.

Very good point, also pointed out in #1577 

> For me, even new layout with all hidden panles

Good idea!

Thanks for the input! I'll have to put some thought into all of this.

**Comment by 3dhavok** [comment]
@oskarkrawczyk i definitely use/used to use the embedded result view for client feedback on quick mockups. I would love to have it back soon or any full frame, unobstructed view of the fins results. If you had a mods popup if there is js, for users to agree to run, that would be fine too

**Comment by greggman** [comment]
I really need to be able to test things on mobile. That doesn't mean I need embed or show to work but it does mean I need some way to get the result to be mobile friendly if that makes any sense. Show and embed did that where as the standard 4 pane editor view is does not.

I'd personally be ok if there was a "click to play" cover so it it's an ad or splash screen for JS fiddle. I click it and the snippet runs. As just one suggestion.

**Comment by rootbeer23** [comment]
I was using the /show function for testing and I can't test on mobile anymore due to the 4 pane redirect. It's laggy and I can't get the feel of how it looks on mobile. If you are able to use a splash screen that says "run code" or anything like that I would appreciate it very much.

**Comment by KacperMadej** [comment]
The pop-up for IE is now leading to an infinite loop and/or is misleading. IE11 suggests trying to open in read-only mode due to lack of support for IE. It fails to load the demo with `/show`. Next, it goes back to the starting page and opens the pop-up with the info again.

**Comment by nms553** [comment]
It's not just me!  I was looking everywhere to see if the "/show" feature was taken away or what happened to it?  I am glad to see an open discussion about it here.  "Show" was the main reason I used JSFiddle, nobody else offers it, and for the same reasons people mentioned above.   I understand how it could have been used and abused, but would LOVE for this feature to come back somehow.  Thanks so much

**Comment by oskarkrawczyk** [comment]
Hey all,

Since getting the new behavior working takes a bit more time than anticipated (some refactoring is required).

I'm temporarily disabling the previously implemented redirect.

Keeping this ticket open until the new click-to-run feature is implemented.

#### Just a note:

Please **DO NOT** use `/embedded/result`, but `/show` instead - yes both, do the same thing, but the former will not be supported and will end up in a redirect when run standalone (outside of the embed `iframe`).

**Comment by oskarkrawczyk** [comment]
Getting there:

<img width="1089" alt="Screen Shot 2020-05-20 at 11 54 28" src="https://user-images.githubusercontent.com/34213/82432816-de135b00-9a90-11ea-91e4-72d936174ab6.png">

**Comment by oskarkrawczyk** [comment]
Just deployed the refactored code.

The `/show` is now called the **Standalone View**, will be documented and integrated into the Editor interface as a maintained feature.

The Standalone View differs UI-wise from the embed, and it'll always require a manual click to run (because we can't have nice things, as explained above):

<img width="1199" alt="Screen Shot 2020-05-22 at 13 22 06" src="https://user-images.githubusercontent.com/34213/82665051-44d07a00-9c33-11ea-82b0-ea32d2b2b6f4.png">

Tests are greelit, and from manual testing all should be working fine. Also downgraded JS so it should run fine on older IE versions.

If you notice something working oddly please let me know in a new ticket.

Thanks to all for chipping into this topic and helping getting this done as a maintained feature.

**Comment by pawelfus** [comment]
Great! Just could you remove "click-to-run" div? I can not click anything on the chart: https://jsfiddle.net/BlackLabel/bo7huqkg/show :)

**Comment by oskarkrawczyk** [comment]
Ha, good catch! That was a last-minute change that I forgot to test 🤫😛

**Comment by mplungjan** [comment]
Has this feature been removed (May/June 2024) ?

**Comment by oskarkrawczyk** [comment]
> Has the `/show/` feature been removed (May/June 2024) ?

@mplungjan https://github.com/jsfiddle/jsfiddle-users/issues/1864#issuecomment-2111984431

**Comment by schweissguth** [comment]
> Perhaps just give us a button that toggles the result pane to take all available space?

I like that idea.  Very grateful Oskar for your support.  Show feature was the best.

**Comment by pawelfus** [comment]
+1 for this button

I had to revisit this issue because every once in a while I have to visit an old demo on a mobile, to test something and it takes time to copy & paste demo to local sources. Even a simple button at the top, next to "Embed" using [Fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) would be great
