### ISSUE TITLE
Adding resources does not work

### ISSUE THREAD

**Issue by karl-police** [jsfiddle/jsfiddle-issues#1630]
See page https://jsfiddle.net/fsx9hLmj/7/

I tried to import ``https://raw.githubusercontent.com/bebraw/colorjoe/master/dist/colorjoe.min.js`` and a .css

but it doesn't work, nor does @import url(styles.css) work or anything else, it just doesn't work.

**Comment by zalun** [comment]
JSFiddle creates a `HEAD` element automatically. 
Please use the Resources tab and make sure the URL contains the `https://` part.

**Comment by karl-police** [comment]
> JSFiddle creates a `HEAD` element automatically.
> Please use the Resources tab and make sure the URL contains the `https://` part.

I did, take a look at https://jsfiddle.net/5uswac0t/ the GIF library
and now take a look what happens if I use the resources tab and include it with script

**Comment by zalun** [comment]
Now it's OK.
Unfortunately GitLab does not allow this:
In Web Console you can see - `The resource from “https://gitlab.com/UniQMG/not.support/-/raw/master/public/blurple/js/lib/gif.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default
