### ISSUE TITLE
RUN sometimes opens a new tab instead of reloading the page

### ISSUE THREAD

**Issue by AMBudnik** [jsfiddle/jsfiddle-issues#1631]
I've just found an interesting issue @oskarkrawczyk  

I've been working on this demo http://jsfiddle.net/AMBudnik/ekz3n2gb/ (running, forking, saving) but when I wanted to use <kbd>RUN</kbd> button for the nth time the page did not reload, it started to open a new tab on my Chrome 84.

Repro
![export](https://user-images.githubusercontent.com/10757813/92115563-e8b0f080-edf2-11ea-8599-8073e7e1ae1e.gif)

Code is correctly cloned to the new tab, but I'd rather get the basic page reload :-)

**The opened tabs URL address**: http://fiddle.jshell.net/_display/
**My demo URL address**: http://jsfiddle.net/AMBudnik/ekz3n2gb/
**My device**: Macbook Air with macOS Catalina 10.15.3
**Browser**: 
* the same sample on FF 80.0.1 shows error for lacking resources 
* Safari works as Chrome

**Comment by oskarkrawczyk** [comment]
This happens when the code tries to break out of the iframe sandbox by changing for example the `parent.name` - I don't see the immediate reason why this should happen with the fiddle provided, but this is most definitely caused by the fiddle code.

Will look into this and pinpoint which part of the code/lib causes this.

**Comment by no-gravity** [comment]
This also happens when you set the variable "name" in a module:

https://jsfiddle.net/x5d1vyo9/
