### ISSUE TITLE
Unclosed HTML comment and script tag within JS pane breaks the site

### ISSUE THREAD

**Issue by thykka** [jsfiddle/jsfiddle-issues#1639]
Steps to reproduce:

1. Create a new blank fiddle

2. Type this into the JS pane (including the quotes, it should be a string as far as JS is concerned):
```javascript
'<!--<script>'
```
3. Save the fiddle

4. Refresh the page

Expected outcome: The page should display the saved fiddle

Actual outcome: The page looks completely broken. There are errors in the browser's console. First error is:

> Uncaught SyntaxError: Invalid regular expression: missing /

**Comment by binki** [comment]
I get a similar issue. If I have something like this in my JavaScript, it escapes from the `<script>/*<![CDATA[*/` ridiculousness:

```js
const x = `</script>`;
// This is a JavaScript comment. However, it still shows up in the Result pane.
```

https://jsfiddle.net/binki/2e0bgfar/

**Comment by oskarkrawczyk** [comment]
No idea how to prevent this from happening so we'll have to live with this for now.

**Comment by binki** [comment]
@oskarkrawczyk Is it a requirement that the script be inline rather than an external resource? When I write JavaScript into jsfiddle, I feel like I shouldn’t have to be aware of the fact that I am writing code that will be placed in an inline `<script>…</script>` block. It [doesn’t look like there is any universal, safe way to escape `<script></script>` contents when the syntax is HTML](https://stackoverflow.com/q/14780858/429091). Could the `src` attribute be used instead? Does that break things?

**Comment by binki** [comment]
More context: https://html.spec.whatwg.org/#restrictions-for-contents-of-script-elements

**Comment by oskarkrawczyk** [comment]
All code has to be inline - that's how the system was designed.

**Comment by binki** [comment]
Not even `data:` URI?

**Comment by binki** [comment]
Or create via DOM and set `textContent` which seems to bypass the HTML parsing issue?

(I do really wish that XML/XHTML had caught on all the more now ;-)).
