### ISSUE TITLE
disable line breaks in code layout or add line bookmark

### ISSUE THREAD

**Issue by foxfoxgo** [jsfiddle/jsfiddle-issues#1644]
Hello,

When you insert some base64 encoded images in css the line breaks make it hard to navigate through the code spanning thousands characters line to hundreds lineS. In fact, even a simple svg code inserted in html that is spanned over multiple lines is harder to read.

Is it possible to disable this auto-formatting or otherwise is it possible to define line bookmarks to quickly navigate through the code (example with np++ just pressing F2)?

thank you

**Comment by ScamCast** [comment]
Was having somewhat of a similar issue when testing out some large JSON. The scrollbar  goes off the page and gets lost in the background making it difficult to navigate around. The scrollbar should be the length of the tabs window while the slider should shrink down instead of getting super big. This is with "wrap lines" turned off. 

https://i.imgur.com/Ob3hxiz.png
https://i.imgur.com/jxzllOS.png
