### ISSUE TITLE
save ... NOT update

### ISSUE THREAD

**Issue by ezmilhouse** [jsfiddle/jsfiddle-issues#20]
hi fiddlers,

i had the chance to present the fiddle to a bunch of co-workers and they played around with it a few hours. after a while they all complained about a missing 'save' option.

the use case was always the same:
- they did some code and pressed '+save' to claim that project
- then they did more coding and eventually pressed 'update' after they accomplished something - versioning was understood (.../xyzTUV/1)
- but in between, when they did an update and added code, they often didn't want to do another 'update' to have those additional lines saved (.../xyzTUV/2), 'cause they felt the code wasn't ready for a next update yet. but of course they didn't want to lose it either - so they asked for a save option within the same version (.../xyzTUV/1).

so, what about adding strg-s for saving without updating?

**Comment by jpdevries** [comment]
was this closed without a fix? I think I'm running into the same issue here.

so you
 - create a fiddle
 - share it on forum(s)
 - make a change

what if you don't want to have to go back to all your forum(s) and edit the link you posted? 

You're basically doing version control but instead of letting people revert back to previous versions you are creating a new fiddle (URL) each time they make a change regardless of if they wanted to or not. 

It's like if git created a new branch every time you made a commit...
