### ISSUE TITLE
embedded view not supported with github integration

### ISSUE THREAD

**Issue by parente** [jsfiddle/jsfiddle-issues#46]
For example:

Demo on the github: http://github.com/zalun/jsFiddleGithubDemo/tree/master/Demo/

URL to jsFiddle: http://jsfiddle.net/gh/get/mootools/1.2/zalun/jsFiddleGithubDemo/tree/master/Demo/

URL to embedded view on jsFiddle would be

http://jsfiddle.net/gh/get/mootools/1.2/zalun/jsFiddleGithubDemo/tree/master/Demo/embedded/

but this does not work because jsFiddle starts looking for the files to show under ../Demo/embedded.

Perhaps ?embedded=true on the URL would be a reasonable solution?

**Comment by craigsnyders** [comment]
Came here looking for this feature. Left disappointed.

**Comment by ondrek** [comment]
I asked if there is any progress since 2011 — it was in 2013. Now it's 2015 and I be like:
"Yeah. I'm patient and I don't need this desperately, but I'll try it in 2017 again ..."

**Comment by tilwinjoy** [comment]
Wow... I was pretty exited when I found github integration because I thought I can have the demo folders in the master branch of my github repository and use it for development, and embed the results in the github page without unnecessarily duplicating the whole thing in gh-pages  branch. I setup the demo structures for like more than 10 components so that I can embed them in github page and then found this...

Neither [embeding docs](http://doc.jsfiddle.net/use/embedding.html) nor [github integration docs](http://doc.jsfiddle.net/use/github.html) says it's impossible to embed a fiddle integrated with github. Please update the docs guys...
