### ISSUE TITLE
https support for serving embedded fiddles?

### ISSUE THREAD

**Issue by tomascassidy** [jsfiddle/jsfiddle-issues#524]
Firefox is now block loading mixed active content on https pages.  This is preventing fiddles from being embedded on https pages as the fiddles are only served via http.

I've noticed it a lot recently as github pages are now only served via https.
eg. http://afarkas.github.io/webshim/demos/demos/forms.html

**Comment by jugglinmike** [comment]
The resolution of this issue is not clear to me. Does the "Archived" label mean that the maintainers are not interested in implementing this feature?

In case anyone might be swayed: my company's weblog contains a number of embedded iframes as live interactive examples in support of the text content. Now that we are serving our content over HTTPS, modern browsers refuse to load the insecure active content.

JSFiddle nominally supports SSL (i.e. requests using HTTPS are served the correct content) but the redirection logic is invalid for that scheme:

```
$ curl -i https://jsfiddle.net/cowboy/jNrVD/embedded/js,result
HTTP/1.1 301 MOVED PERMANENTLY
Server: nginx
Date: Wed, 19 Aug 2015 14:28:24 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Location: http://jsfiddle.net/cowboy/jNrVD/embedded/js%2Cresult/
```

It would be great to keep using JSFiddle on our blog, but I understand if this feature is not a priority. Even in that case, it would be helpful to get some clarity on the maintainers' perspective here.

Thanks for the great service!

**Comment by jugglinmike** [comment]
To anyone experiencing this issue: appending a trailing slash to the URL avoids the redirect. I've followed up with https://github.com/jsfiddle/jsfiddle-issues/issues/624 to discuss this

**Comment by oskarkrawczyk** [comment]
Bringing back from the archive. 

@zalun Any chance you could have a look into this?
