### ISSUE TITLE
npm-jsfiddle

### ISSUE THREAD

**Issue by rk08** [jsfiddle/jsfiddle-issues#543]
Is there any way to include npm package into js fiddle like we include external libraries

**Comment by baconface** [comment]
I hope this doesn't come off as spammy. If so please delete. But I needed to do the same because I wanted to test some NPMs as front end code as if it was running on NW.js. So I wrote a NW.js project that loads and gives the appropriate permissions to jsFiddle. Just make a folder in the root path of the binary called "node_modules" and import your NPM packages into there. Then you will then be able to require them in the JS panel. I don't have binaries posted yet so you will have to follow the instructions to get it running. And you will only be able to require and execute node.js/io.js modules compatible with NW.js. Thanks jsFiddle for making a pretty awesome tool!

https://github.com/baconface/nwFiddle

**Comment by oskarkrawczyk** [comment]
Including NPM packages will be added when JSFiddle is rewritten – archiving this issue for now.
