### ISSUE TITLE
Add OpenUI5 as supported JS library

### ISSUE THREAD

**Issue by agraebe** [jsfiddle/jsfiddle-issues#572]
Would love to see OpenUI5 as a supported JS library under Frameworks & Extensions!

Here are some details on OpenUI5:
www.openui5.org
https://github.com/SAP/openui5/

Here's the link to the latest version for mobile: 
OpenUI5 (latest, mobile) - https://openui5.hana.ondemand.com/resources/sap-ui-core.js

And here's a fiddle with OpenUI5: http://jsfiddle.net/urp0pfqq/

Thanks a lot! :)

**Comment by dandv** [comment]
:+1:

**Comment by petrunov** [comment]
(y)

**Comment by petrunov** [comment]
:+1:

**Comment by fabiopagoti** [comment]
It would be great to use this.

**Comment by laughsmile** [comment]
Please

**Comment by ivanfemia** [comment]
up!

**Comment by oskarkrawczyk** [comment]
Done

**Comment by akudev** [comment]
That's great, thanks! 

Right now the script include seems to be:

`<script type="text/javascript" src="//openui5.hana.ondemand.com/1.30.10/resources/sap-ui-core.js"></script>`

Two remarks: 
1.) version "1.30.10" is up-to-date right now, but referencing `//openui5.hana.ondemand.com/resources/sap-ui-core.js` would always load the latest stable version and would remove the need to update frequently.
2.) UI5 is modular and comes with several control libraries. Usually developers specify which libraries they intend to use by adding the `data-sap-ui-libs` attribute to this script tag. A very common configuration would be `data-sap-ui-libs="sap.m,sap.ui.layout,sap.ui.unified" `.  Not having this configuration means the libraries need to be loaded explicitly, which is not obvious and not so common in UI5. Almost the same goes for the visual theme to be used. Developers would usually add the `data-sap-ui-theme="sap_bluecrystal"` attribute to the script tag. Without it, the app will not look good because a very basic fallback theme is used.

Regards
Andreas

**Comment by oskarkrawczyk** [comment]
@akudev 

1. Fixed. My mistake. Sorry.
2. There's no way to predefine the script attributes from the framework level on our end. Every user would have to do this by hand from the **Fiddle options** and **Framework script attribute** input.

**Comment by akudev** [comment]
Thanks!

I see... so the steps to create an OpenUI5 app after selecting "OpenUI5" in the dropdown would be:

1.) Open the Fiddle Options at the left and enter the following into the "Framework &lt;script> attribute" field:
`data-sap-ui-libs="sap.m,sap.ui.layout,sap.ui.unified" data-sap-ui-theme="sap_bluecrystal"`
2.) Either create some HTML where to place the UI5 controls in the "HTML" area, or enter the following into the "Body tag" field:
`<body id="content" class="sapUiBody">`
3.) You are good to go, e.g. write the following code into the "JavaScript" area:
`new sap.m.Button({text: "Hello"}).placeAt("content");`

**Comment by oskarkrawczyk** [comment]
@akudev correct!

**Comment by agraebe** [comment]
@oskarkrawczyk Thanks! :)
