### ISSUE TITLE
Consider adding a button to remove or apply the local draft

### ISSUE THREAD

**Issue by oskarkrawczyk** [jsfiddle/jsfiddle-issues#672]
Local drafts are great, but can cause some confusion when you want to reset the unsaved code simply by reloading the browser.

Currently it'll load the local draft because the editor doesn't want you to lose any changes.

Maybe adding info/button after reloading and applying the draft would resolve some confusion.

**Comment by Mottie** [comment]
+1 for this change.... 

Actually, having an indicator showing that the *local draft is active* would really help. Yesterday I got very frustrated because I use a jsFiddle base file that shows all of my plugin options... if I update the fiddle then go back to that base file, only the update will show! I ended up recreating the base file before I realized that this turned out to be a new feature, not a bug LOL.

**Comment by oskarkrawczyk** [comment]
Yeah, I see this is causing a bit of confusion. I think I'll just make an info and a button to apply the local draft.

**Comment by 2pha** [comment]
+1
I just spent about 20 minutes trying to figure out what was going on until I read about the local storage thing. Then spend about 10 minutes trying to find how to turn it off before resorting to deleting in dev tools

**Comment by oskarkrawczyk** [comment]
Changed the behavior. Local drafts now need to be applied manually.

<img width="877" alt="screen shot 2015-12-14 at 21 30 39" src="https://cloud.githubusercontent.com/assets/34213/11795281/2208d3c6-a2b6-11e5-9e45-2c2d640a5cdc.png">

**Comment by Mottie** [comment]
Awesome thanks!... is there any way to clear them?

**Comment by oskarkrawczyk** [comment]
@Mottie Yep, it's simply using `localStorage`.

Just delete the items from it.

<img width="779" alt="screen shot 2015-12-14 at 23 05 35" src="https://cloud.githubusercontent.com/assets/34213/11795513/5532dfde-a2b7-11e5-913f-b38c56d8c21c.png">
