### ISSUE TITLE
Embed script snippet not working as expected

### ISSUE THREAD

**Issue by freethan** [jsfiddle/jsfiddle-issues#732]
Hi,

we came across this issue where copying the embed `<script>` string of a fiddle would not work when embedding it to an HTML page by throwing a `jsfiddle.net/:19 Uncaught TypeError: Cannot read property 'parentNode' of null` (it could not find the original `<script>` and then replace it with an `<iframe>`).

This is how the embed script code looks like for this fiddle ([http://jsfiddle.net/j0kgfx1t/](http://jsfiddle.net/j0kgfx1t/)): `<script async src="//jsfiddle.net/j0kgfx1t/embed/js,html,css,result/dark/"></script>`

> The reason for it is in the actual JavaScript source code, where it tries to match the embed script tag and then fire-off the creation of an iframe. The source code is trying to find a script starting with `https://` instead of matching `//` which what the JSFiddle UI displayed when generating the embed code.

I would propose to continue using // as a way of being protocol agnostic (http / https) when being embedded and basing the matching query off a `data-` attribute.

e.g. given this fiddle: http://jsfiddle.net/j0kgfx1t/

the embed script should look like 
`<script async src="//jsfiddle.net/j0kgfx1t/embed/js,html,css,result/dark/" data-jsfiddle-id="j0kgfx1t"></script>`

and the script code itself (https://jsfiddle.net/j0kgfx1t/embed/js,html,css,result/dark/) modified so this `target = document.querySelector("script[src*='" + uriOriginal + "']");` turns into:
`target = document.querySelector("script[data-jsfiddle-id='" + currentSlug + "']");`

**Comment by selfthinker** [comment]
A workaround is to just add the protocol, e.g. `<script async src="https://jsfiddle.net/j0kgfx1t/embed/js,html,css,result/dark/"></script>`. At least that makes it work while this hasn't been fixed yet.

**Comment by timroes** [comment]
This is a pretty annoying bug, that the offered script tag just doesn't work, due to the above mentioned problem.

In general the embed script is "quite stupid". If you forget the slash at the end it won't find the script tag again. Also I have the problem, that apparently something (I am not sure if it's jQuery or what) adds a query parameter with the timestamp to the file when inserting the script tag dynamically. To be more clear:

I add the `<script src="correct-url" async></script>` tag with jQuery later on into the HTML, which will cause the browser to request the file `correct-url?_=1234567890` which can be seen in the network panel. So the resulting embed.js will try to find a script tag with that source in it, but the script tag I added still has only the correct-url as a src and won't be found. Besides I don't know what causes that wired behavior of requesting a different URL, than that in the src attribute, it would also help here if jsfiddle could somehow be "more clever" when trying to find the element.

Suggestion: when generating the embed script tag in the jsfiddle frontend just add some `data-jsfiddleid="1o2o3o4o"` to the script tag, and use that to find the matching script tag again.

**Comment by oskarkrawczyk** [comment]
Thanks for the input guys. Will look into this.
