### ISSUE TITLE
Inserted indentation character not exact

### ISSUE THREAD

**Issue by yckart** [jsfiddle/jsfiddle-issues#734]
The editor inserts sometimes a tab instead of a space, and a space instead of a tab (~~depends on the setting~~). This occurs, to be exactly, at each _odd_ iteration and in all panels.

I've played a bit around and can reproduce this behaviour. Tested this on a blank line, but would do the same, if the cursor is at an _even_ position:

<kbd>TAB</kbd> inserts `\9`
<kbd>TAB</kbd> + <kbd>SPACE</kbd> `\9\20`

<kbd>SPACE</kbd> inserts `\20`
<kbd>SPACE</kbd> + <kbd>TAB</kbd> inserts `\20\20`

This is maybe an issue with CodeMirror, don't know yet...

**Comment by 42degrees** [comment]
Selections also make a difference.  If you are just in the whitespace of a line (just caret, no selection) it inserts tab.  Note that this is with the "Indent with tabs" configuration checkbox unchecked.

However, if you have a selection of any kind then the tab key inserts spaces (you can select any single character in a row, or multiple whole lines, and tab will insert spaces instead of tabs).  

If I check the "Indent with tabs" checkbox then it not only inserts tabs with or without a select, but with a selection it converts all leading whitespace to tabs (any evenly divisible white space, depending on the size set for a tab, with the remainder as spaces).  I don't use tabs, but if I did, this seems like perfectly reasonable behavior (it cleans up extra single spaces as it goes).

@yckart I  could not reproduce the behavior that you reported with the space + tab.  For me it inserted a space followed by a tab (regardless of the setting of "Indent with tabs").

**Comment by oskarkrawczyk** [comment]
I tried fixing this many times, with next to no luck. Annoying as hell, but it'll stay as it is in this version. The rewrite will have completely refactored editor which will not have this issue.
