### ISSUE TITLE
Implement name-agnostic redirection

### ISSUE THREAD

**Issue by Gabrielr47** [jsfiddle/jsfiddle-issues#741]
Recently I faced this problem:

I changed the username on JSFiddle, and all links
that was already posted at StackOverflow are broken
now.

So, My friend Bacco  suggest  that JSFiddle ignore names, as
e.g. codepen does.

Example of wrong name on codepen:

    http://codepen.io/THISISNOTMYNAME/pen/BoEPXY

Example of no name on codepen:

    http://codepen.io/pen/BoEPXY

You can see that both work,

It would be very nice if JSFiddle adopts such behaviour.

Best Regards
Gabriel Rodrigues

**Comment by oskarkrawczyk** [comment]
JSFiddle will not adopt this behavior.

**Comment by Bacco** [comment]
Bad bad decision. So, a simple account rename will kill all the links we have shared. Time to move to another service.

**Comment by baconface** [comment]
Might as well leave Github. Renaming your account here will also change your repository links. (Any redirections are temporary.)

**Comment by Bacco** [comment]
@baconface and you think it's good that way? You have an unique identifier, isn't that enough? So, you have CodePen as good example, GitHub as bad example, and use the 2nd one as reference? What's your point?

**Comment by baconface** [comment]
There is a pretty logical way Github does it. A project name example is hosted by a user name bob as bob/example. Then John forks it and it is john/example. Then Tom makes a new repo called example at tom/example. So who does /example belong to? It breaks the way the URL system works by removing the unique identifier.

I can't tell you for sure why JSFiddle does it the way they do it. But obviously it is part of how it works. They could even be preventing hash collusion by not changing their behavior. Assuming that they have something in place they aren't doing or changing it won't break anything is just that. An assumption.

So weather I believe it is a good way or not is moot if one way works and the other is potentially going to break it or avoided by design.

**Comment by baconface** [comment]
To be honest I just posted my initial response because of your original response before you edited it. I just wanted to point out the irony of threatening to leave a service by using another service that is doing the exact same behavior as your issue.

**Comment by Bacco** [comment]
@baconface I noticed it sounded wrong, so I edited (curiously, It seems I did it before your reply, but you saw It anyway). Also, my initial tone was influenced by the short "no" followed by the quick close (not that it justifies it), but the focus was really the points I mentioned, not my personal satisfaction. Also, I'm fully aware that one leaving the service is irrelevant, so mentioning it is at least silly in the first place. About collisions, I thought the same before posting, but noted that the ID structure was unique even with names, so I saw it as an opportunity for a better behaviour, but, in the end, who knows... Hope you understand my point ov view, and thanks for your time clarifying yours. Regards.

**Comment by oskarkrawczyk** [comment]
We're not in the business of adopting behavior that looks like a bug.

Logical thing is that permalinks will break if you decide on changing your username – that's what everyone would expect, that's how the whole internet works.

Locking this topic. There's nothing to be said here that will change this decision.
