### ISSUE TITLE
webstorage

### ISSUE THREAD

**Issue by texirv0203** [jsfiddle/jsfiddle-issues#743]
Hi,

Is it possible to test webstorage in fiiddle...since when i give submit i see error...how to fix it

https://jsfiddle.net/r977y9zb/18/

**Comment by oskarkrawczyk** [comment]
Nothing in JSFiddle is preventing testing storage.

What you're trying to do here is submit a form to the render frame – something that only JSFiddle editor is allowed to do.

If you want to play with forms in JSFiddle, be sure to do a `event.preventDefault()` on submit so that there's no actual submitting done.
