### ISSUE TITLE
Similar / Complimentary issues

### ISSUE THREAD

**Issue by Lewiscowles1986** [jsfiddle/jsfiddle-issues#834]
Apologies if this has been raised internally, but some of the issues are complimentary and almost make others irrelevant, or unnecessary.

#### Git Integration

https://trello.com/c/39zZZzs6/44-export-a-fiddle-as-a-github-gist (the one I favor) seems to address

 * https://trello.com/c/mczcvR9n/4-sync-fiddles-with-github (I feel JSFiddle is more suited to gist)
 * https://trello.com/c/ehQqTKCU/19-social-module-commenting-on-fiddles-rating (again gist linked could facilitate via gist.github.com)
 * https://trello.com/c/It8w1RGl/55-ability-to-view-a-diff-between-revisions (gist supports this)
 * https://trello.com/c/MlFT83qO/51-bookmarking-starring-fiddles (gist supports starring gists, so someone could use gist to navigate to jsFiddle)

Admittedly I'm using starring as an indicator of a rating, and you wouldn't have to do this, but I think it warrants consideration for the effort it could save building your own something, rather than encouraging (potentially promoting in some cases) use of tools that already exist.

**Comment by oskarkrawczyk** [comment]
@Lewiscowles1986 The question is, would we not want a feature just because some other webapp has it? 

It's all up for community vote, if they decide a feature is needed, and we approve, it's going to happen. 

JSFiddle is one thing, Github another, no reason why one or the other wouldn't have similar features.

Also, not everyone is using Github.
