### ISSUE TITLE
Use Monaco editor for JSFiddle

### ISSUE THREAD

**Issue by IllusionMH** [jsfiddle/jsfiddle-issues#835]
Since Microsoft released Monaco Editor to open source (https://microsoft.github.io/monaco-editor/index.html) JSFiddle can benefit from reach editing capabilities as well as code completion features.

**Comment by oskarkrawczyk** [comment]
@IllusionMH I've seen the announcement yesterday on HN. 

It's way too early for any serious adoption, since we don't know if Microsoft doesn't decide to kill off the project in 6 months.

We don't know if the community will be interested in writing plugins/extensions, or will Microsoft end up maintaining the code themselves. 

It's simply too early, let's see what happens. 

For now we're going to stick with CodeMirror or move to Ace in the 2.0 rewrite of JSFiddle.

I agree with one thing, having their autocomplete would be super-nice.

**Comment by IllusionMH** [comment]
@oskarkrawczyk thanks for feedback.
This was feature suggestion for future, and mainly because of great autocomplete, because it is thing that I'm missing now.

Would wait to see autocomplete from CodeMirror or Ace. Their implementation is good enough for "one file" code (as most fiddles are), and it should be possible to extend it for libraries.
