### ISSUE TITLE
Allow Dynamic Embed

### ISSUE THREAD

**Issue by ccorcos** [jsfiddle/jsfiddle-issues#902]
I like to write articles using markdown and I want to have interactive code samples, but I dont want to create a js fiddle and create an embedded iframe every time, I'd really like to be able to write the code in my article and then with a compiling step, load that code into an embedded jsfiddle. That way, its easier to make edits to the article and everything is in one place. I can even create a static version of the article without iframes if someone wants a PDF.

Is there any way to embed code in url params that get loaded into the fiddle?

Thanks

Chet

**Comment by oskarkrawczyk** [comment]
There's no way to do what you need. Embeds by design need to be hosed on our end.

If you'd like for people to play around with the code, you can use this [https://github.com/jsfiddle/jsfiddle-post.js](https://github.com/jsfiddle/jsfiddle-post.js) – it'll add a link "Edit in JSFiddle" (code is sent via POST to JSFiddle).

**Comment by ccorcos** [comment]
Yeah that's basically what I want except it would be nice to display the
code alongside the HTML result. Then readers can play with the demo and
then go to jsfiddle to edit the code if they want.

Just curious, why is it by design that the code has to be hosted?
