### ISSUE TITLE
Allow 'Tidy' to use tabs instead of spaces when selected as a preference in settings

### ISSUE THREAD

**Issue by GoOtterGo** [jsfiddle/jsfiddle-issues#910]

**Comment by oskarkrawczyk** [comment]
Unfortunately the codebase for the current JSFiddle version is frozen and no minor issues will be addressed. 

We're all hands on the rewrite and in order to get it out sooner rather than later, we can't spend time on addressing this in the legacy codebase.

The new rewritten codebase will not have this issue.
