### ISSUE TITLE
Easy changes to improve the viewing of embedded codes in mobiles

### ISSUE THREAD

**Issue by alexandremagro** [jsfiddle/jsfiddle-issues#913]
In Embed component, if you use all the tabs (Result, HTML, CSS, Javascript) and the width of page is narrow, it's split in two rows and some tabs overrides the code, sometimes getting illegible and unworkable use. This sometimes occurs when I try use embedded JSFiddle code in my blog, and test it in my phone.

My suggestion is to change the tab name "JavaScript" to "JS" and remove "Edit in jsFiddle" in header, keeping the logo.

**Comment by sdkcarlos** [comment]
In the following example the "Result" tab overrides the code:

![screenshot_20161224-083552](https://cloud.githubusercontent.com/assets/11634719/21465852/2fc94c4a-c9b4-11e6-9b4a-bf25a2bbc694.png)

**Comment by Wunder-Wulfe** [comment]
i think they should have the result tab at the bottom because after u go through the code u should be able to test it

**Comment by marcomezzavilla** [comment]
Today I also came across this problem.
I add here some considerations, even if the issue is a couple of years old.

Most of the header on mobile devices is occupied by the logo and the "Edit in JSFiddle" link:

![current (iphone SE example)](https://user-images.githubusercontent.com/8218010/98481657-025c2300-21fc-11eb-974c-a73580ded2be.png)

Maybe it would make sense to keep only the logo or a more synthetic version of the link.

![only logo](https://user-images.githubusercontent.com/8218010/98481667-16078980-21fc-11eb-8d14-6b9e05df6c8c.png)

![logo + link](https://user-images.githubusercontent.com/8218010/98481670-199b1080-21fc-11eb-95dd-6867e33e66c5.png)

In addition, for an even more versatile solution, the editor header may have a horizontal overflow so that it can scroll.
Keeping the logo always visible on the right (in case it is a requirement) should not be too tricky.

![smaller device](https://user-images.githubusercontent.com/8218010/98481712-772f5d00-21fc-11eb-9059-177ec7e232b3.png)
