### ISSUE TITLE
regeneratorRuntime not included when using babel

### ISSUE THREAD

**Issue by jimmywarting** [jsfiddle/jsfiddle-issues#923]
Would be nice to have it included... Right now some browser supports generators, but with babel this just breaks my code (works better without it)
```
Uncaught ReferenceError: regeneratorRuntime is not defined(…)
```

**Comment by oskarkrawczyk** [comment]
@jimmywarting can you provide some context? I don't know what `regeneratorRuntime` is, and what would you expect to be the correct behavior.

**Comment by jimmywarting** [comment]
The simpliest thing you can do is this: https://jsfiddle.net/3x83r580/

```js
function* foo(){}
```

You could also do 
```js
async function foo(){}
```

**Comment by jimmywarting** [comment]
https://babeljs.io/docs/plugins/transform-regenerator/

**Comment by oskarkrawczyk** [comment]
Had a deeper look into this, and it doesn't seem like a quick fix:

- `transform-regenerator` requires `transform-runtime`
- `transform-runtime` needs `require` to be present (https://github.com/babel/babel-standalone/issues/4#issuecomment-172407902)
- `require` is not present in JSFiddle since we're transpiling stuff on the fly in frontend with `babel-standalone` for browsers

I've spent some time trying getting this to work with very little success.

If you manage to get it working with `babel-standalone`, let me know and I'll put it into JSFiddle.

**Comment by jimmywarting** [comment]
So why did you close the issue? it's still a problem that's unresolved

**Comment by oskarkrawczyk** [comment]
Codebase for the current JSFiddle version is frozen – no features will be added.

**Comment by jimmywarting** [comment]
... Well i don't see it as a feature. I see it as a fix to something that is broken and has to be resolved. so i still think the issue should be open until it has been resolved. 

adding [this](https://cdn.rawgit.com/facebook/regenerator/master/packages/regenerator-runtime/runtime.js) as resource/dependencies helps at least https://jsfiddle.net/zkbb8u3e/

**Comment by oskarkrawczyk** [comment]
It's not an issue, since Babel-standalone doesn't support this out of the box, so nothing is really broken. Especially since you've just pointed out that including external resource adds the feature.

**Comment by jimmywarting** [comment]
Don't think everyone should have to go and look for this external resource to add it manually. You should include it when ppl chose babel as there runtime
