### ISSUE TITLE
Bug: Valid HTML can get marked as red

### ISSUE THREAD

**Issue by chrisjj** [jsfiddle/jsfiddle-issues#935]
Despite that this HTML 

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<title>Title of the document</title>
</head>

<body>
<div>
<table>
<tr><td>kjasd kjasdh kajsdh alkjsdh lajksdhlas</td>
<tr><td>
  <ul class="container">
    <li class="left"><a href="#">ListItem1</a></li>
    <li class="right"><a href="#">ListItem2</a></li>
  </ul>
</table>
</div> 
```

http://pastebin.com/BipXrFFH

is valid http://i.imgur.com/3GmvAIa.png , JSFiddle marks two tags in read:

http://i.imgur.com/diMC4oO.png
![image](https://cloud.githubusercontent.com/assets/6157073/20671481/6300e8b4-b575-11e6-997d-b96e87d03647.png)

**Comment by oskarkrawczyk** [comment]
That's not valid HTML (`ul` inside of a `table`). Also, there's no need for `doctype`, `head`, `body`, `html` (both latter are not closed) inside of JSFiddle.

**Comment by chrisjj** [comment]
> That's not valid HTML (ul inside of a table).

UL inside a table is valid. See validation here http://i.imgur.com/3GmvAIa.png 

Also the bug appears even with no UL https://jsfiddle.net/hbszf61x/ .

> Also, there's no need for doctype, head, body, html (both latter are not closed) inside of JSFiddle.

The need here was to ensure I was supplying valid and validated code.

**Comment by oskarkrawczyk** [comment]
It's not valid. This is valid: https://jsfiddle.net/8L3o1q5w/

**Comment by chrisjj** [comment]
> It's not valid. 

The W3C validator says it is valid. http://i.imgur.com/3GmvAIa.png

> This is valid

Adding a redundant </td> worksaround the JSFiddle bug but is not required for valid code.

**Comment by oskarkrawczyk** [comment]
It's not a workaround it's Basics of HTML. `ul` cannot be a direct descendant of `table` in HTML5.

Not valid:

<img width="776" alt="screen shot 2016-11-28 at 16 11 02" src="https://cloud.githubusercontent.com/assets/34213/20673397/53829008-b585-11e6-9cf5-8a2ca3d85294.png">

Valid:

<img width="767" alt="screen shot 2016-11-28 at 16 10 35" src="https://cloud.githubusercontent.com/assets/34213/20673403/56654a68-b585-11e6-979e-08a85bbb11f8.png">

Closing this discussion as it's going nowhere since this is not a bug.
