### ISSUE TITLE
Claim fiddle after login after saving it as anonymous

### ISSUE THREAD

**Issue by rudiedirkx** [jsfiddle/jsfiddle-issues#94]
I use jsfiddle a lot and sometimes I'm not logged in when I start it, so I get some code running and save it a few times. All of it is not saved to my user though.

The solution is easey, but a waste of anonymous fiddles: log in, go back to fiddle, fork it.

I'd like to see the option to 'claim' previously made (as in max 30 minutes or 2 hours ago) fiddles that were made in this session. Maybe with some kind of secret fiddle-specific key that's saved in a cookie or something.

**Comment by pcfreak30** [comment]
No updates on this? Would like this too so i can trash fiddles.

**Comment by oskarkrawczyk** [comment]
Rewrite will have this

**Comment by andrewteeoh** [comment]
Hi, I've been tracking this for a little while now. Will the rewrite of JSFiddle still have this? I no longer see a task on the roadmap for it.

**Comment by christophfriedrich** [comment]
I always used JSFiddle anonymously, until a few minutes ago I finally signed up because I wanted to properly keep track of the fiddle I just wrote. I was very surprised to NOT find the fiddle in "my fiddles" right away (I expected the website to automatically understand that it's mine after refreshing the fiddle page), and even more surprised that there is not even a more manual option to do this.
**So this use case is indeed one that would make more people sign up if done properly!**
