### ISSUE TITLE
Resize the Embed Window

### ISSUE THREAD

**Issue by jel111** [jsfiddle/jsfiddle-issues#964]
I like the layout of the Embed window much better. Either allow to go full screen or resize that window. Or just be able to change the style of the editor.Move the windows around and have different themes. I think that is the main reason I do not use Fiddle is because of the layout. Why do you send us to Trello when you need to put the issue here?

**Comment by oskarkrawczyk** [comment]
If the embed it embedded using `<script>` the height will readjust to its contents. Having the ability to resize the height manually would be quite difficult since it's an iframe – I don't see a use-case for this.

Not sure what you mean by saying "move windows", I assume tabs, and you can already do that while generating the embed:

`<script async src="//jsfiddle.net/oskar/7960xwsj/embed/js,css,result/"></script>` - order of items in the last URL segment.

We have two themes for the embed: dark and light, for now we're not planning on adding new ones:

<img width="907" alt="screen shot 2017-02-09 at 08 08 29" src="https://cloud.githubusercontent.com/assets/34213/22772785/f5c31192-ee9e-11e6-8cab-728b9d1ae466.png">

**Comment by jel111** [comment]
What I mean is if you could resize that window you could keep it as an overlay and just use that versus the native layout. I like the way it looks much better but that may be a personal thing or the fact that I am used to most other editors.

**Comment by oskarkrawczyk** [comment]
@jel111 You can set your own size to the `iframe` (in which case you need to embed the `iframe` not `script` version).
